"""
LaTeX analysis report composer; chart generation (matplotlib -> PDF embed).
"""
from __future__ import annotations
import os, tempfile, shutil
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import statistics
from euler_omr.core.analysis import AnalysisReport
from euler_omr.core.template_compiler import TemplateCompiler
import structlog

logger = structlog.get_logger(__name__)


class ReportBuilder:
    @staticmethod
    def build(report: AnalysisReport, output_path: str, log_callback=None) -> str:
        _log = log_callback or (lambda m, l: None)
        tmp = tempfile.mkdtemp(prefix="euler_report_")
        try:
            # ── Chart 1: Overall histogram ──
            fig, ax = plt.subplots(figsize=(8, 4))
            bins = range(0, report.max_score + 2)
            ax.hist(report.overall_scores, bins=bins, color="#117A65",
                    edgecolor="#1B4F72", alpha=0.8, rwidth=0.85)
            ax.set_xlabel("Score", fontsize=11, fontweight="bold", color="#1B4F72")
            ax.set_ylabel("Number of Students", fontsize=11, fontweight="bold", color="#1B4F72")
            ax.set_title("Overall Grade Distribution", fontsize=13, fontweight="bold", color="#1B4F72")
            ax.set_xticks(range(0, report.max_score + 1))
            ax.grid(axis='y', linestyle='--', alpha=0.5)
            hist_path = os.path.join(tmp, "histogram.png")
            fig.savefig(hist_path, dpi=150, bbox_inches="tight")
            plt.close(fig)

            # ── Chart 2: Version mean comparison bar ──
            if report.version_stats:
                fig, ax = plt.subplots(figsize=(8, 4))
                vers = [vs.version for vs in report.version_stats]
                means = [vs.mean for vs in report.version_stats]
                bars = ax.bar(vers, means, color="#117A65", edgecolor="#1B4F72", alpha=0.7, width=0.6)
                ax.set_xlabel("Version", fontsize=11, fontweight="bold", color="#1B4F72")
                ax.set_ylabel("Mean Score", fontsize=11, fontweight="bold", color="#1B4F72")
                ax.set_title("Version Mean Score Comparison", fontsize=13, fontweight="bold", color="#1B4F72")
                ax.axhline(y=report.overall_mean, color="red", linestyle="--", linewidth=2,
                           label=f"Overall Mean ({report.overall_mean})")
                ax.grid(axis='y', linestyle='--', alpha=0.5)
                ax.legend()
                bar_path = os.path.join(tmp, "version_bar.png")
                fig.savefig(bar_path, dpi=150, bbox_inches="tight")
                plt.close(fig)

            _log("Charts generated", "INFO")

            # ═══════════════════════════════════════════════════════════
            #  Build LaTeX report
            # ═══════════════════════════════════════════════════════════
            ms = report.max_score
            pct_mean = round(report.overall_mean / ms * 100, 1) if ms > 0 else 0

            # LaTeX Template as a raw string to ensure no f-string expansion errors
            latex_template = r"""\documentclass[12pt, a4paper]{article}

\usepackage[margin=2.5cm]{geometry}
\usepackage{booktabs}
\usepackage{array}
\usepackage{xcolor}
\usepackage{colortbl}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{hyperref}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{multirow}
\usepackage{enumitem}
\usepackage{tcolorbox}
\usepackage{float}
\usepackage{caption}

\definecolor{primary}{HTML}{1B4F72}
\definecolor{accent}{HTML}{117A65}
\definecolor{lightgray}{HTML}{F2F3F4}
\definecolor{medgray}{HTML}{BDC3C7}
\definecolor{danger}{HTML}{C0392B}
\definecolor{warning}{HTML}{D4AC0D}
\definecolor{success}{HTML}{1E8449}
\definecolor{rowA}{HTML}{EBF5FB}
\definecolor{rowB}{HTML}{FFFFFF}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\color{primary}\textbf{Euler OMR} --- Psychometric Evaluation Report}
\fancyhead[R]{\small\color{medgray}Generated by Euler OMR}
\fancyfoot[C]{\small\color{medgray}\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0pt}

\titleformat{\section}{\large\bfseries\color{primary}}{\thesection.}{0.5em}{}[\titrule]
\titleformat{\subsection}{\normalsize\bfseries\color{accent}}{\thesubsection}{0.5em}{}

\hypersetup{
	colorlinks=true,
	linkcolor=primary,
	urlcolor=accent
}

\tcbuselibrary{skins, breakable}
\newtcolorbox{summarybox}{
	enhanced,
	colback=lightgray,
	colframe=primary,
	boxrule=1pt,
	arc=4pt,
	left=8pt, right=8pt, top=6pt, bottom=6pt,
	title={\bfseries\color{white} Executive Summary},
	fonttitle=\bfseries,
	coltitle=white,
	attach boxed title to top left={yshift=-2mm, xshift=4mm},
	boxed title style={colback=primary, arc=3pt}
}

\begin{document}

\begin{titlepage}
	\centering
	\vspace*{2cm}
	{\Huge\bfseries\color{primary} Euler OMR\par}
	\vspace{0.4cm}
	{\LARGE\color{accent} Assessment Analytics and \\ Psychometric Evaluation Report\par}
	\vspace{1cm}
	\textcolor{medgray}{\rule{0.6\textwidth}{0.6pt}}
	\vspace{0.8cm}
	
	\begin{tcolorbox}[width=0.75\textwidth, colback=lightgray, colframe=medgray, arc=4pt, boxrule=0.6pt]
		\centering
		\begin{tabular}{rl}
			\textbf{Total Students:} & __TOTAL_STUDENTS__ \\
			\textbf{Overall Mean:}   & __OVERALL_MEAN__ / __MAX_SCORE__ \quad (__MEAN_PCT__\%) \\
			\textbf{Median Score:}   & __MEDIAN__ \\
			\textbf{Standard Deviation:} & __STD_DEV__ \\
			\textbf{Score Range:}    & __MIN_SCORE__ -- __MAX_SCORE_VAL__ \\
			\textbf{Cronbach's Alpha / KR-20:} & __CRONBACH_ALPHA__ \\
			\textbf{Split-Half Reliability:} & __SPLIT_HALF__ \\
		\end{tabular}
	\end{tcolorbox}
	
	\vfill
	{\small\color{medgray} Generated for institutional academic evaluation.}
\end{titlepage}

\section{Reliability Analysis}
\begin{table}[H]
	\centering
	\caption{Psychometric Reliability Coefficients}
	\renewcommand{\arraystretch}{1.35}
	\begin{tabular}{lcl}
		\toprule
		\rowcolor{primary}
		\color{white}\textbf{Metric} & \color{white}\textbf{Value} & \color{white}\textbf{Standard Interpretation} \\ \midrule
		\rowcolor{rowA} Cronbach's Alpha & __CRONBACH_ALPHA__ & Good to Excellent ($>0.70$) \\
		\rowcolor{rowB} KR-20 & __KR20__ & Good to Excellent ($>0.70$) \\
		\rowcolor{rowA} Split-Half Reliability & __SPLIT_HALF__ & High correlation indicates internal consistency \\
		\bottomrule
	\end{tabular}
\end{table}

\section{Executive Recommendations}
\begin{tcolorbox}[colback=lightgray, colframe=primary, arc=3pt, boxrule=0.8pt]
	\textbf{Assessment Quality Diagnostics:}\\
	__RECOMMENDATIONS__
\end{tcolorbox}

\section{Overall Statistics \& Score Distribution}
\begin{center}
	\begin{tcolorbox}[width=0.7\textwidth, colback=rowA, colframe=primary, arc=4pt, boxrule=0.8pt]
		\centering
		\renewcommand{\arraystretch}{1.4}
		\begin{tabular}{>{\bfseries}l r}
			\toprule
			\multicolumn{1}{c}{\color{primary}\textbf{Statistic}} &
			\multicolumn{1}{c}{\color{primary}\textbf{Value}} \\
			\midrule
			Total Students  & __TOTAL_STUDENTS__ \\
			Mean            & __OVERALL_MEAN__ / __MAX_SCORE__ \quad (__MEAN_PCT__\%) \\
			Median          & __MEDIAN__ \\
			Std Deviation   & __STD_DEV__ \\
			Range           & __MIN_SCORE__ -- __MAX_SCORE_VAL__ \\
			\bottomrule
		\end{tabular}
	\end{tcolorbox}
\end{center}

\begin{figure}[H]
	\centering
	\includegraphics[width=0.82\textwidth]{histogram.png}
	\caption{Score distribution curve (Frequency across students)}
\end{figure}

\newpage
\section{Advanced Item Analysis}
\begin{table}[H]
	\centering
	\caption{Item performance metrics across all students}
	\renewcommand{\arraystretch}{1.3}
	\begin{tabular}{ccccccc}
		\toprule
		\rowcolor{primary}
		\color{white}\textbf{Q} & \color{white}\textbf{Key} & \color{white}\textbf{p-value} & \color{white}\textbf{Discrimination} & \color{white}\textbf{Pt-Biserial} & \color{white}\textbf{Distractor Eff.} & \color{white}\textbf{Status} \\ \midrule
__ITEM_PSY_ROWS__
		\bottomrule
	\end{tabular}
\end{table}

\begin{tcolorbox}[colback=lightgray, colframe=primary, arc=3pt, boxrule=0.8pt]
	\textbf{Psychometrics Standard Reference:}\\
	\textbf{p-value (Difficulty):} Proportion correct. Easy $>0.75$, Moderate $0.30 - 0.75$, Hard $<0.30$.\\
	\textbf{Discrimination Index (D):} Difference between top and bottom 27\% groups. Excellent $\ge 0.40$, Acceptable $0.30 - 0.39$, Review required $<0.30$.\\
	\textbf{Pt-Biserial Correlation:} Point-biserial correlation to overall score. Highly discriminating if $\ge 0.25$.
\end{tcolorbox}

\section{Topic / Learning Outcomes Analytics}
\begin{table}[H]
	\centering
	\caption{Mastery and performance broken down by assessment domain}
	\renewcommand{\arraystretch}{1.3}
	\begin{tabular}{lclcc}
		\toprule
		\rowcolor{primary}
		\color{white}\textbf{Domain ID} & \color{white}\textbf{Items Included} & \color{white}\textbf{Difficulty} & \color{white}\textbf{Discrimination} & \color{white}\textbf{Status} \\ \midrule
__TOPIC_ROWS__
		\bottomrule
	\end{tabular}
\end{table}

\newpage
\section{Student Analytics Summary}
\begin{table}[H]
	\centering
	\caption{Overall individual performance ranking and bands}
	\renewcommand{\arraystretch}{1.25}
	\begin{tabular}{llccc}
		\toprule
		\rowcolor{primary}
		\color{white}\textbf{Student ID} & \color{white}\textbf{Score} & \color{white}\textbf{Percentile} & \color{white}\textbf{Z-Score} & \color{white}\textbf{Mastery Classification} \\ \midrule
__STUDENT_ROWS__
		\bottomrule
	\end{tabular}
\end{table}

\section{Version Equivalence \& Analytics}
\begin{table}[H]
	\centering
	\caption{Descriptive statistics broken down by exam version}
	\renewcommand{\arraystretch}{1.3}
	\begin{tabular}{cccccccc}
		\toprule
		\rowcolor{primary}
		\color{white}\textbf{Version} &
		\color{white}\textbf{N} &
		\color{white}\textbf{Mean} &
		\color{white}\textbf{\%} &
		\color{white}\textbf{Median} &
		\color{white}\textbf{Std Dev} &
		\color{white}\textbf{Min} &
		\color{white}\textbf{Max} \\ \midrule
__VERSION_STATS_ROWS__
		\bottomrule
	\end{tabular}
\end{table}

\begin{table}[H]
	\centering
	\caption{Equivalence Tests across Exam Versions}
	\renewcommand{\arraystretch}{1.35}
	\begin{tabular}{lccc}
		\toprule
		\rowcolor{primary}
		\color{white}\textbf{Test} & \color{white}\textbf{Statistic} & \color{white}\textbf{p-value} & \color{white}\textbf{Result Interpretation} \\ \midrule
		\rowcolor{rowA} ANOVA (parametric) & $F = __ANOVA_F__$ & $__ANOVA_P__$ & __ANOVA_RESULT__ \\
		\rowcolor{rowB} Kruskal-Wallis & $H = __KRUSKAL_H__$ & $__KRUSKAL_P__$ & __KRUSKAL_RESULT__ \\
		\bottomrule
	\end{tabular}
\end{table}

\begin{tcolorbox}[colback=lightgray, colframe=primary, arc=3pt, boxrule=0.8pt]
	\textbf{Version Equivalence Interpretation:}\\
	$p < 0.05 \implies$ Statistically significant differences detected among versions.\\
	$p \ge 0.05 \implies$ No statistically significant differences detected among versions.
\end{tcolorbox}

\begin{summarybox}
	\begin{itemize}[leftmargin=*, itemsep=4pt]
		\item \textbf{Total Students:} __TOTAL_STUDENTS__
		\item \textbf{Overall Mean:} __OVERALL_MEAN__ / __MAX_SCORE__ \quad (__MEAN_PCT__\%)
		\item \textbf{Overall Median:} __MEDIAN__
		\item \textbf{Cronbach's Alpha:} __CRONBACH_ALPHA__
		\item \textbf{Split-Half Reliability:} __SPLIT_HALF__
		\item \textbf{Version ANOVA p-value:} __ANOVA_P__
	\end{itemize}
\end{summarybox}

\end{document}
"""

            # Dynamic Row Replacements
            # 1. Item Psychometrics Rows
            psy_rows = []
            for idx, psy in enumerate(report.item_psychometrics):
                bg = r"\rowcolor{rowA} " if idx % 2 == 0 else r"\rowcolor{rowB} "
                key_str = ", ".join(psy.correct_keys) if psy.correct_keys else "--"
                # Use plain raw string replacement
                psy_rows.append(f"{bg} Q{psy.question_idx+1} & {key_str} & {psy.p_value} & {psy.discrimination_index} & {psy.point_biserial} & {psy.distractor_efficiency}\\% & {psy.quality_class} \\\\")
            
            # 2. Topic Analysis Rows
            topic_rows = []
            for idx, t in enumerate(getattr(report, 'topic_analyses', [])):
                bg = r"\rowcolor{rowA} " if idx % 2 == 0 else r"\rowcolor{rowB} "
                topic_rows.append(f"{bg} {t['topic_id']} & {t['items']} & {t['mean_difficulty']} & {t['mean_discrimination']} & {t['status']} \\\\")

            # 3. Student Analysis Rows (Top 25 for report compactness)
            student_rows = []
            stu_list = getattr(report, 'student_analytics', [])
            for idx, s in enumerate(stu_list[:25]):
                bg = r"\rowcolor{rowA} " if idx % 2 == 0 else r"\rowcolor{rowB} "
                student_rows.append(f"{bg} {s['student_id']} & {s['score']} & {s['percentile']}\\% & {s['z_score']} & {s['mastery']} \\\\")

            # 4. Version Stats Rows
            version_rows = []
            for idx, vs in enumerate(report.version_stats):
                bg = r"\rowcolor{rowA} " if idx % 2 == 0 else r"\rowcolor{rowB} "
                pct = round(vs.mean / ms * 100, 1) if ms > 0 else 0
                version_rows.append(f"{bg} {vs.version} & {vs.count} & {vs.mean} & {pct}\\% & {vs.median} & {vs.stddev} & {vs.min_score} & {vs.max_score_val} \\\\")

            # 5. Build Recommendations Text
            recs = []
            # Low discrimination warning
            has_low_d = any(psy.discrimination_index < 0.10 for psy in report.item_psychometrics)
            if has_low_d:
                recs.append("--- One or more items in this assessment show a low discrimination index (D < 0.10) and require review.")
            
            # Easy/Hard test overall skew
            if pct_mean > 75:
                recs.append("--- The assessment is skewed towards easy items.")
            elif pct_mean < 45:
                recs.append("--- The assessment is skewed towards hard items.")
            else:
                recs.append("--- The overall exam difficulty is within normal range.")

            # Version Equivalence warning
            if report.anova_p < 0.05:
                recs.append("--- Version inequality detected via ANOVA. Review version balancing.")
            else:
                recs.append("--- Version equivalence confirmed via ANOVA.")

            recommendations_str = " \\\\\n".join(recs)

            # Perform string replacements on the template
            latex = latex_template
            latex = latex.replace("__TOTAL_STUDENTS__", str(report.total_students))
            latex = latex.replace("__MAX_SCORE__", str(ms))
            latex = latex.replace("__OVERALL_MEAN__", str(report.overall_mean))
            latex = latex.replace("__MEAN_PCT__", str(pct_mean))
            latex = latex.replace("__MEDIAN__", str(report.overall_median))
            latex = latex.replace("__STD_DEV__", str(report.overall_stddev))
            latex = latex.replace("__MIN_SCORE__", str(report.overall_min))
            latex = latex.replace("__MAX_SCORE_VAL__", str(report.overall_max))
            latex = latex.replace("__CRONBACH_ALPHA__", str(getattr(report, 'cronbach_alpha', 0.0)))
            latex = latex.replace("__KR20__", str(getattr(report, 'kr20', 0.0)))
            latex = latex.replace("__SPLIT_HALF__", str(getattr(report, 'split_half_reliability', 0.0)))
            latex = latex.replace("__RECOMMENDATIONS__", recommendations_str)
            latex = latex.replace("__ITEM_PSY_ROWS__", "\n".join(psy_rows))
            latex = latex.replace("__TOPIC_ROWS__", "\n".join(topic_rows))
            latex = latex.replace("__STUDENT_ROWS__", "\n".join(student_rows))
            latex = latex.replace("__VERSION_STATS_ROWS__", "\n".join(version_rows))
            latex = latex.replace("__ANOVA_F__", str(round(report.anova_f, 3)))
            latex = latex.replace("__ANOVA_P__", str(round(report.anova_p, 3)))
            latex = latex.replace("__ANOVA_RESULT__", r"\textcolor{danger}{\textbf{Significant diff}}" if report.anova_p < 0.05 else r"\textcolor{success}{\textbf{No sig diff}}")
            latex = latex.replace("__KRUSKAL_H__", str(round(report.kruskal_h, 3)))
            latex = latex.replace("__KRUSKAL_P__", str(round(report.kruskal_p, 3)))
            latex = latex.replace("__KRUSKAL_RESULT__", r"\textcolor{danger}{\textbf{Significant diff}}" if report.kruskal_p < 0.05 else r"\textcolor{success}{\textbf{No sig diff}}")

            tex_path = os.path.join(tmp, "report.tex")
            with open(tex_path, "w", encoding="utf-8") as f:
                f.write(latex)

            pdflatex = TemplateCompiler.find_pdflatex()
            if pdflatex:
                import subprocess
                # Run pdflatex twice for table of contents / correct page numbering
                subprocess.run([pdflatex, "-interaction=nonstopmode", "report.tex"], cwd=tmp, capture_output=True)
                subprocess.run([pdflatex, "-interaction=nonstopmode", "report.tex"], cwd=tmp, capture_output=True)
                pdf_src = os.path.join(tmp, "report.pdf")
                if os.path.exists(pdf_src):
                    shutil.copy2(pdf_src, output_path)
                    _log(f"Analysis report saved to {output_path}", "INFO")
                    return output_path
            _log("pdflatex not available for report compilation", "WARNING")
            return ""
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
