blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/MustafaMahmoud-ILE/EulerOMR/discussions
    about: Please confirm that your issue is a bug or feature request. If you just have a question, please use Discussions.
